version: '3.8'

services:
  dev:
    image: node:16
    user: "1000:1000"
    tty: true
    volumes:
      - .:/src
      - /tmp:/root
    command: "npm run dev"
    working_dir: /src
  test-watch:
    image: node:16
    user: "1000:1000"
    tty: true
    command: "npm run test:watch"
    volumes:
      - .:/src
    working_dir: /src
